### ISSUE TITLE
apt error after finish install vlc

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#10] opened 2019-07-10 19:55 UTC
![Screenshot_20190710_195435](https://user-images.githubusercontent.com/840070/61000269-99854200-a34c-11e9-9a55-97030bd3ff01.png)

**Comment by llelectronics** [comment] 2019-07-11 10:49
I am not able to reproduce this issue.This is what I got after installing a package
![image](https://user-images.githubusercontent.com/3415572/61045021-41951c80-a3da-11e9-81e5-b19e482e28d8.png)

**Comment by ScarlettGatelyMoore** [comment] 2019-07-11 14:38
Also not able to reproduce.
![Screenshot_20190711_073503](https://user-images.githubusercontent.com/1056501/61060005-c8cc9b00-a3ae-11e9-993a-714b46816d2c.png)

**Comment by llelectronics** [comment] 2019-07-12 08:44
I was able to reproduce it now on the netrunner-20190711.1528-amd64.hybrid.iso images live system. 
I did not refresh the package list and just tried installing qmmp. It gives the Changes applied dialog and if you click on close it will prompt the warning. 
After refreshing the package list the warning will not appear again.

**Comment by star-buck** [comment] 2019-07-31 11:56
will need to test on next RC Iso without testing enabled

**Comment by llelectronics** [comment] 2019-08-01 11:31
Tested on 20190731.1549 image and cannot reproduce. 
I installed qmmp after installation of the system and it worked fine.

**Comment by llelectronics** [comment] 2019-08-05 10:35
Still works on **netrunner-20190805.0503**

**Comment by star-buck** [comment] 2019-08-15 11:00
not here:
![Screenshot_20190815_105928](https://user-images.githubusercontent.com/840070/63090796-ed86d600-bf4b-11e9-9167-95b9df740406.png)

installed from live usb

**Comment by ScarlettGatelyMoore** [comment] 2019-08-18 13:18
Now reproducible. Live VM open synaptic and select vlc ( no apt update ) and this warning shows up. Incidently /var/cache/apt/archives/partial is root:root whereas on an updated system it is _apt:root
There is tons of bug reports on this issue but none specific to ours. They seem to be missing _apt user, but we are not. Still researching...

**Comment by ScarlettGatelyMoore** [comment] 2019-08-18 16:51
Downloading new ISO to test. But in the meantime, my new install on hardware did not get this. Only live is affected. Did not update, installed vlc via synaptic fine.

**Comment by ScarlettGatelyMoore** [comment] 2019-08-18 17:17
It is a space issue on live.

Note
Users of apt-secure may find issues when using
aptitude
or
apt-get
. For apt-get,
you can use
apt-get update --allow-releaseinfo-change
.
4.4.3 Makesureyouhavesufficientspacefortheupgrade
You have to make sure before upgrading your system that you will have sufficient hard disk space when
you start the full system upgrade described in Section 
4.4.5
. First, any package needed for installation
that is fetched from the network is stored in
/var/cache/apt/archives
(and the
partial/
subdi-
rectory, during download), so you must make sure you have enough space on the file system partition
that holds
/var/
to temporarily download the packages that will be installed in your system. After
the download, you will probably need more space in other file system partitions in order to both install
upgraded packages (which might contain bigger binaries or more data) and new packages that will be
pulled in for the upgrade. If your system does not have sufficient space you might end up with an
incomplete upgrade that is difficult to recover from.

I can confirm this as when I allocated more memory to the VM vlc was able to complete the install despite the warning. It also does not happen on a fresh install to hardware. Changing ownership in hook did not change anything.

**Comment by ScarlettGatelyMoore** [comment] 2019-08-19 02:38
I have tried everything I can think of. It still ends up root:root I have tried chown _apt in chroot, and binary hooks, I tried a boot script. It still ends up root:root. There are tons of bug reports out there on this and it is synaptic. If you use apt update and apt install, it works. If you allocate at least 2G ram, the install still goes through despite error. This does not happen at all on an installed system. It is someting to do with the lack of space and the way ms fonts are installed. Sorry, I am out of ideas. Maybe @llelectronics will have better luck in the morning. Calling it a night.

**Comment by llelectronics** [comment] 2019-08-19 10:25
I don't see a way to fix this as this happens randomly apparently and synaptic seems to be almost unmaintained as this bug seems very old and no one thought it might be good fixing it. 
For what its worth I think it is totally wrong for synaptic showing Warnings by apt as error messages in general.

**Comment by ScarlettGatelyMoore** [comment] 2019-08-19 13:16
Thank you @llelectronics . I was on the right track and you got it it done. I am happy to report this is fixed.
![Screenshot_debian10-clone_2019-08-19_06:14:32](https://user-images.githubusercontent.com/1056501/63268339-d47e6d80-c248-11e9-9e9f-3242889a92ab.png)

**Comment by ScarlettGatelyMoore** [comment] 2019-08-19 13:22
or not - I closed success window and warning window was still there.

**Comment by ScarlettGatelyMoore** [comment] 2019-08-19 18:39
Last fix did the trick! 
![Screenshot_debian10-clone_2019-08-19_11:38:06](https://user-images.githubusercontent.com/1056501/63290312-0d810700-c276-11e9-981e-099173e543a1.png)

**Closed** 2019-08-20 20:09 UTC
Labels: blocker, bug, ready for QA
