### ISSUE TITLE
dolphin: single click activated, should be double click

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-19.08#26] opened 2019-07-27 09:46 UTC

**Comment by star-buck** [comment] 2019-07-27 17:37
this seems a looknfeel setting, as when i switched it seems to be now doubleclick?

**Comment by ScarlettGatelyMoore** [comment] 2019-07-28 19:13
I can't seem to reproduce this :( it take me two clicks to open things in dolphin. I also checked the kdeglobals files and SingleClick=false is set in ~/.config and usr/share/default-settings

**Comment by star-buck** [comment] 2019-07-28 19:14
It was single click here after installation.

**Comment by llelectronics** [comment] 2019-07-29 08:58
The issue seems to be the same we had for 19.01. We had to ship our own color scheme and also set single click to false in the colors file aswell as setting nothing would default to the "global" default.
This bug should be fixed in newer Plasma but we are still hitting it apparently.

**Comment by llelectronics** [comment] 2019-07-29 09:20
Should be fixed now.

**Closed** 2019-07-30 09:30 UTC
Labels: bug, ready for QA
